## Transmission coefficients

Transmission coefficients ($\kappa$) take quantum tunneling effects into
account in reaction rate constants.

In [1]:
import overreact as rx
from overreact import constants

rx.tunnel.wigner(266.5144)

1.0689203364495672

In [2]:
kappa = rx.tunnel.wigner(1000.0)
kappa

1.9702999975616722

In [3]:
import numpy as np

delta_gibbs = rx.get_delta(
    [[0, 0, 0],
     [-1, 0, 1],
     [1, 0, -1],
     [0, 0, 0],
     [0, 0, 0]],
    [0., 5., -10., 5., 7.5])
delta_gibbs

array([-15.,   0.,  15.])

Now comes Eyring's equation

In [4]:
T = 298.15
K = np.exp(- delta_gibbs / (constants.R * T / constants.kcal))
k = kappa * (constants.k * T / constants.h) * K
K, k

(array([9.88726786e+10, 1.00000000e+00, 1.01140175e-11]),
 array([1.21023783e+24, 1.22403666e+13, 1.23799281e+02]))

In [5]:
k / kappa

array([6.14240385e+23, 6.21243799e+12, 6.28327065e+01])